POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Lusia",
    "lastName": "Smith",
    "email": "lusiSmith@gmail.com",
    "password": "qwertyqwerty",
    "birthday": "1980-08-15",
    "gender": "female"
}
